export const CHECKUPS = {
  REGISTRATION: 1,
  SPECTACLE_CORRECTION: 2,
  SLIT_LAMP_CHECKUP: 3,
  NERVE_ASSESSMENT: 4,
  BP_SUGAR_TEST: 5,
  OPERATION_RECOMMENDATION: 6,
} as const;

export const CHECKUP_STATUS = {
  WAITING: "WAITING",
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  PENDING: "PENDING",
  SKIPPED: "SKIPPED",
} as const;

export const ROLES = {
  ADMIN: "ADMIN",
  RECEPTION: "RECEPTION",
  VOLUNTEER: "VOLUNTEER",
  DOCTOR: "DOCTOR",
} as const;

export const ROOM_CHECKUPS: Record<string, number> = {
  "spectacle-correction": CHECKUPS.SPECTACLE_CORRECTION,
  "slit-lamp": CHECKUPS.SLIT_LAMP_CHECKUP,
  nerve: CHECKUPS.NERVE_ASSESSMENT,
  "bp-sugar": CHECKUPS.BP_SUGAR_TEST,
  operation: CHECKUPS.OPERATION_RECOMMENDATION,
};